import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  CONFORMANCE_FIXTURES,
  DECLARED_SYNTHETIC_SECRETS,
  FIXTURE_OUTBOX_ACTIONS,
  UE5_FIXTURE_DIRECTORY,
  type ConformanceFixture,
} from "../../packages/contracts/src/ue5/fixtures";
import { UE5_CONTRACT_STATUS, UE5_CONTRACT_VERSION } from "../../packages/contracts/src/ue5/wire";

/**
 * GENERATES THE UE5 CONFORMANCE FIXTURE PACK.
 *
 *   pnpm contracts:fixtures
 *
 * The sibling of `emit-ue5-contract.ts`, with the same discipline and a
 * different job. That generator publishes the *shape* of the protocol — an
 * OpenAPI document and a JSON Schema per component. This one publishes the
 * *behaviour*: twenty-one complete exchanges, each with the per-event outbox
 * decision the response must produce.
 *
 * The distinction is the reason both exist. A schema can say that a `200`
 * carries a `results` array. It cannot say that a submitted event absent from
 * that array is still unacknowledged, that a result for an id nobody sent
 * acknowledges nothing, or that two results for one id must fail safe. Those are
 * the rules an implementation gets wrong, and they are only expressible as
 * worked examples.
 *
 * Everything is written from `packages/contracts/src/ue5/fixtures.ts` and
 * nothing by hand. `fixtures.test.ts` regenerates the pack in memory and fails
 * if the committed files differ, so an edit to a fixture that is not accompanied
 * by a regeneration cannot reach a commit.
 *
 * Deterministic by construction: no clock, no randomness, no environment, no
 * network. It reads TypeScript and writes files.
 */

const ROOT = join(import.meta.dirname, "..", "..");
const OUT = join(ROOT, "docs", "ue5-contract", UE5_FIXTURE_DIRECTORY);

/**
 * What the three outbox actions mean, published inside the pack.
 *
 * A conformance runner in another language reads `index.json` and nothing else.
 * A vocabulary defined only in this repository's TypeScript would be a
 * vocabulary Akhilesh has to guess at.
 */
const ACTION_MEANINGS: Readonly<Record<string, string>> = Object.freeze({
  remove:
    "Acknowledged. The server holds the fact and the outbox row may be erased. Reached by a " +
    "per-event `accepted` and by a per-event `duplicate`, and by nothing else.",
  retain: "Not acknowledged. The event stays queued and will be offered to the transport again.",
  quarantine:
    "Kept on disk with its reason and never retried. Counted in the heartbeat so an operator " +
    "can see it. Never deleted.",
});

/** Everything the generator produces, as text, keyed by path under `OUT`. */
export function generatedFixtureFiles(): Map<string, string> {
  const files = new Map<string, string>();

  files.set("index.json", `${JSON.stringify(packIndex(), null, 2)}\n`);
  for (const fixture of CONFORMANCE_FIXTURES) {
    files.set(`${fixture.name}.json`, `${JSON.stringify(oneFixtureDocument(fixture), null, 2)}\n`);
  }
  files.set("README.md", readme());
  return files;
}

/** The stanza every document repeats, so a single file is self-describing. */
function contractStanza(): Record<string, unknown> {
  return {
    version: UE5_CONTRACT_VERSION,
    status: UE5_CONTRACT_STATUS,
    generatedBy: "pnpm contracts:fixtures",
    note: "Generated from packages/contracts/src/ue5/fixtures.ts. Do not edit by hand.",
  };
}

function packIndex(): Record<string, unknown> {
  return {
    contract: contractStanza(),
    outboxActions: Object.fromEntries(
      FIXTURE_OUTBOX_ACTIONS.map((action) => [action, ACTION_MEANINGS[action] ?? ""]),
    ),
    /*
     * Published so a conformance runner can assert the same thing this
     * repository asserts: that no credential-shaped value in the pack is
     * anything but one of these.
     */
    syntheticSecrets: DECLARED_SYNTHETIC_SECRETS,
    fixtureCount: CONFORMANCE_FIXTURES.length,
    fixtures: CONFORMANCE_FIXTURES,
  };
}

function oneFixtureDocument(fixture: ConformanceFixture): Record<string, unknown> {
  return { contract: contractStanza(), fixture };
}

/* ============================================================ the README */

function readme(): string {
  const lines: string[] = [
    "<!-- GENERATED by `pnpm contracts:fixtures`. Do not edit by hand. -->",
    "",
    "# UE5 conformance fixture pack",
    "",
    `**Contract:** \`${UE5_CONTRACT_VERSION}\` · **Status:** ${UE5_CONTRACT_STATUS} · **Fixtures:** ${CONFORMANCE_FIXTURES.length}`,
    "",
    "Every exchange a conforming plugin must handle, as data. `index.json` holds the whole pack;",
    "each fixture is also a standalone file named after it. Nothing here requires reading the",
    "backend source, and a drift test fails if these files and that source disagree.",
    "",
    "## How to run it",
    "",
    "For each fixture: build the request exactly as `request` states, feed `response` to the",
    "transport as if it came off the wire, and compare what the outbox did against",
    "`expectedOutboxActions` — **keyed by `event_id`, never by array position**. Then compare the",
    "sending loop's next state against `expectedSending`.",
    "",
    "Every response body validates against the published schema in `../schemas/`, with exactly",
    'one deliberate exception, marked `"responseValidates": false`.',
    "",
    "## The three outbox actions",
    "",
    "| Action | Meaning |",
    "| --- | --- |",
  ];
  for (const action of FIXTURE_OUTBOX_ACTIONS) {
    lines.push(`| \`${action}\` | ${ACTION_MEANINGS[action] ?? ""} |`);
  }

  lines.push(
    "",
    "There is deliberately no fourth action, and in particular no `discard`. No response",
    "anywhere in this pack may result in an event ceasing to exist.",
    "",
    "## The four that carry the most weight",
    "",
    "The rest of the pack confirms behaviour a careful implementation already has. These four are",
    "the ones that are wrong in practice, and each is wrong in a way that is silent:",
    "",
    "| Fixture | The rule |",
    "| --- | --- |",
    "| `ingest-missing-result` | A submitted event with no result of its own is **retained**. Silence is not acceptance. |",
    "| `ingest-foreign-result-id` | A result whose `event_id` was not submitted acknowledges **nothing**, and must never be matched to another queued event. |",
    "| `ingest-conflicting-duplicate-result` | Two results for one `event_id` **retain**. Fail safe. |",
    "| `ingest-malformed-2xx-body` | A `2xx` whose body does not validate acknowledges **zero** events. |",
    "",
    "All four have the same shape: the response looks plausible, the counters agree with",
    "themselves, and an implementation that pairs results to queued events by array position or",
    "by count acknowledges the wrong events without ever raising an error.",
    "",
    "## One anti-pattern, because it is live",
    "",
    "`ingest-accepted-is-a-count-not-a-list` carries a valid canonical body **and** a",
    "`counterExample` that a parser migrating from an `accepted_ids` field expects. `accepted` is",
    "an integer count. It is not a list of ids, and no field in `BatchResponse` lists accepted",
    "ids — acknowledgement comes only from `results[].event_id`.",
    "",
    "A parser that binds `accepted_ids` to `accepted` reads a number where it expects an array,",
    "and in every language that coerces, the failure is quiet: the outbox acknowledges nothing",
    "while the server stores everything.",
    "",
    "## Credentials",
    "",
    "Every secret-shaped value in this pack is synthetic and fixed:",
    "",
  );
  for (const secret of DECLARED_SYNTHETIC_SECRETS) lines.push(`- \`${secret}\``);

  lines.push(
    "",
    "Neither is a well-formed credential — a real source token is `obs.<selector>.<secret>` — so",
    "nothing here can be pasted into a client and appear to work. A test sweeps the generated",
    "pack and fails if any other credential-shaped value appears in it.",
    "",
    "## The fixtures",
    "",
    "| Fixture | Status | Why |",
    "| --- | --- | --- |",
  );
  for (const fixture of CONFORMANCE_FIXTURES) {
    lines.push(
      `| [\`${fixture.name}\`](./${fixture.name}.json) | ${fixture.response.status} | ${escapePipes(fixture.why)} |`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function escapePipes(text: string): string {
  return text.replace(/\|/g, "\\|");
}

/* ============================================================ the CLI body */

function write(): void {
  /*
   * Only this subtree is cleared, and it is cleared whole. `emit-ue5-contract.ts`
   * owns everything else under `docs/ue5-contract/` and leaves `fixtures/` alone;
   * the two generators must not be able to delete each other's output.
   */
  rmSync(OUT, { recursive: true, force: true });
  const files = generatedFixtureFiles();
  for (const [relative, contents] of files) {
    const target = join(OUT, relative);
    mkdirSync(join(target, ".."), { recursive: true });
    writeFileSync(target, contents, "utf8");
  }
  console.log(`wrote ${files.size} files to docs/ue5-contract/${UE5_FIXTURE_DIRECTORY}/`);
}

/** Every path currently on disk under the pack directory, for the drift test. */
export function committedFixtureFiles(): readonly string[] {
  if (!existsSync(OUT)) return [];
  const found: string[] = [];
  for (const entry of readdirSync(OUT, { withFileTypes: true, recursive: true })) {
    if (!entry.isFile()) continue;
    const parent = entry.parentPath.slice(OUT.length + 1).replace(/\\/g, "/");
    found.push(parent === "" ? entry.name : `${parent}/${entry.name}`);
  }
  return found.sort();
}

/** Where the pack lives, so a test does not have to rebuild the path. */
export const FIXTURE_PACK_DIRECTORY = OUT;

const invokedDirectly = process.argv[1]?.endsWith("emit-fixtures.ts") ?? false;
if (invokedDirectly) write();
