import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  buildOpenApiDocument,
  componentJsonSchemas,
} from "../../packages/contracts/src/ue5/openapi";
import { EVENT_REJECTIONS, REQUEST_FAILURES } from "../../packages/contracts/src/ue5/errors";
import {
  CLASSIFICATIONS,
  CONTRACT_RULES,
  classificationCounts,
} from "../../packages/contracts/src/ue5/traceability";
import { UE5_CONTRACT_STATUS, UE5_CONTRACT_VERSION } from "../../packages/contracts/src/ue5/wire";

/**
 * GENERATES THE PUBLISHED UE5 CONTRACT ARTEFACTS.
 *
 *   pnpm contracts:ue5
 *
 * Everything under `docs/ue5-contract/` is written from the Zod schemas and the
 * traceability table, never by hand. That is the same arrangement `pnpm matrix`
 * already uses for the measurement matrix, and for the same reason: a
 * description maintained beside an implementation is two things that agree until
 * somebody edits one of them.
 *
 * `generated.test.ts` regenerates all of it in memory and fails if the committed
 * files differ, so a schema change that is not accompanied by a regeneration
 * cannot reach a commit.
 *
 * Nothing here reaches a network, a database or a vendor. It reads TypeScript
 * and writes files.
 */

const ROOT = join(import.meta.dirname, "..", "..");
const OUT = join(ROOT, "docs", "ue5-contract");

/** Everything the generator produces, as text, keyed by path under `OUT`. */
export function generatedArtefacts(): Map<string, string> {
  const files = new Map<string, string>();

  files.set("openapi.json", `${JSON.stringify(buildOpenApiDocument(), null, 2)}\n`);

  for (const [name, schema] of Object.entries(componentJsonSchemas())) {
    files.set(
      `schemas/${name}.schema.json`,
      `${JSON.stringify({ $schema: "https://json-schema.org/draft/2020-12/schema", $id: `https://observer.madspace.dev/ue5/${UE5_CONTRACT_VERSION}/${name}.schema.json`, title: name, ...schema }, null, 2)}\n`,
    );
  }

  files.set("traceability.md", traceabilityMarkdown());
  files.set("error-model.md", errorModelMarkdown());
  return files;
}

const BANNER = (what: string) =>
  [
    `<!-- GENERATED by \`pnpm contracts:ue5\`. Do not edit by hand. -->`,
    "",
    `# ${what}`,
    "",
    `**Contract:** \`${UE5_CONTRACT_VERSION}\` · **Status:** ${UE5_CONTRACT_STATUS}`,
    "",
    "Generated from `packages/contracts/src/ue5/`. A drift test fails if this file and the",
    "source disagree, so what follows is what the code actually enforces rather than what a",
    "document once said it would.",
    "",
  ].join("\n");

function traceabilityMarkdown(): string {
  const counts = classificationCounts();
  const lines: string[] = [BANNER("UE5 contract traceability")];

  lines.push("## Counts", "");
  lines.push("| Classification | Rules |", "| --- | --- |");
  for (const classification of CLASSIFICATIONS) {
    lines.push(`| \`${classification}\` | ${counts[classification]} |`);
  }
  lines.push("", `**Total:** ${CONTRACT_RULES.length}`, "");

  lines.push(
    "Every `LOCKED_FROM_BRIEF` row cites the section of the architecture brief it comes from.",
    "Every `DERIVED_FROM_LOCKED_RULE` row names the locked rules it follows from. Nothing",
    "`PROPOSED` may cite the brief — a proposal borrowing that authority is exactly what this",
    "table exists to prevent.",
    "",
  );

  for (const classification of CLASSIFICATIONS) {
    const rules = CONTRACT_RULES.filter((rule) => rule.classification === classification);
    if (rules.length === 0) continue;
    lines.push(`## ${classification}`, "");
    lines.push(
      "| Id | Rule | Authority | Owner | Blocks | Where |",
      "| --- | --- | --- | --- | --- | --- |",
    );
    for (const rule of rules) {
      const authority =
        rule.briefSection ??
        (rule.derivedFrom.length > 0 ? rule.derivedFrom.map((id) => `\`${id}\``).join(", ") : "—");
      const blocks = rule.blocks.length > 0 ? rule.blocks.join(", ") : "—";
      lines.push(
        `| \`${rule.id}\` | ${escapePipes(rule.statement)} | ${authority} | ${rule.owner} | ${blocks} | \`${rule.where}\` |`,
      );
    }
    lines.push("");
  }
  return `${lines.join("\n")}`;
}

function errorModelMarkdown(): string {
  const lines: string[] = [BANNER("UE5 contract error model")];

  lines.push(
    "## The rule the rest of this depends on",
    "",
    "> **The HTTP status says whether the batch was processed. It never says whether the",
    "> events were accepted.**",
    "",
    "`200` means the batch was processed — read the per-event results, even when every event",
    "in it was rejected. Any non-2xx means nothing was stored and the whole batch is safe to",
    "resend unchanged.",
    "",
    "## Request level",
    "",
    "| Code | HTTP | Meaning | Retryable | Outbox | Sending | Operator |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  );
  for (const failure of REQUEST_FAILURES) {
    lines.push(
      `| \`${failure.code}\` | ${failure.httpStatus} | ${escapePipes(failure.meaning)} | ${yesNo(failure.retryable)} | \`${failure.outbox}\` | \`${failure.sending}\` | ${yesNo(failure.operatorRequired)} |`,
    );
  }

  lines.push(
    "",
    "## Event level",
    "",
    "| Code | Meaning | Retryable | Outbox | Sending | Operator |",
    "| --- | --- | --- | --- | --- | --- |",
  );
  for (const rejection of EVENT_REJECTIONS) {
    lines.push(
      `| \`${rejection.code}\` | ${escapePipes(rejection.meaning)} | ${yesNo(rejection.retryable)} | \`${rejection.outbox}\` | \`${rejection.sending}\` | ${yesNo(rejection.operatorRequired)} |`,
    );
  }

  lines.push(
    "",
    "## Codes this build has never heard of",
    "",
    "| Situation | Retryable | Outbox | Sending |",
    "| --- | --- | --- | --- |",
    "| Unrecognised **event** rejection code | no | `quarantine` | `continue` |",
    "| Unrecognised **4xx** | no | `quarantine` | `continue` |",
    "| Unrecognised other status | yes | `retain` | `backoff` |",
    "| No response at all (timeout, reset, lost acknowledgement) | yes | `retain` | `backoff` |",
    "",
    "An unrecognised event code is treated as non-retryable **whatever the server said about**",
    "**`retryable`**. A client that retries something it cannot interpret retries for ever, and",
    "a quarantined event an operator can see is a better failure than an infinite loop nobody",
    "notices.",
    "",
    "## Rationale, per code",
    "",
  );
  for (const failure of REQUEST_FAILURES) {
    lines.push(`**\`${failure.code}\`** — ${failure.rationale}`, "");
  }
  for (const rejection of EVENT_REJECTIONS) {
    lines.push(`**\`${rejection.code}\`** — ${rejection.rationale}`, "");
  }
  return lines.join("\n");
}

function escapePipes(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function yesNo(value: boolean): string {
  return value ? "yes" : "no";
}

/* ============================================================ the CLI body */

function write(): void {
  rmSync(OUT, { recursive: true, force: true });
  const files = generatedArtefacts();
  for (const [relative, contents] of files) {
    const target = join(OUT, relative);
    mkdirSync(join(target, ".."), { recursive: true });
    writeFileSync(target, contents, "utf8");
  }
  console.log(`wrote ${files.size} files to docs/ue5-contract/`);
}

/** What is on disk now, for the drift test. */
export function committedArtefact(relative: string): string | null {
  try {
    return readFileSync(join(OUT, relative), "utf8");
  } catch {
    return null;
  }
}

const invokedDirectly = process.argv[1]?.endsWith("emit-ue5-contract.ts") ?? false;
if (invokedDirectly) write();
