import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { generatedArtefacts } from "../../../../scripts/contracts/emit-ue5-contract";
import { buildOpenApiDocument } from "../../src/ue5/openapi";
import { UE5_FIXTURE_DIRECTORY } from "../../src/ue5/fixtures";

/**
 * THE PUBLISHED CONTRACT MATCHES THE CODE THAT ENFORCES IT.
 *
 * `docs/ue5-contract/` is generated by `pnpm contracts:ue5`, exactly as
 * `docs/measurement-matrix.md` is generated by `pnpm matrix`, and for the same
 * reason: a description maintained beside an implementation is two things that
 * agree until the afternoon somebody edits one of them.
 *
 * This regenerates everything in memory and compares. A schema change that
 * reaches a commit without a regeneration fails here — which matters more than
 * usual, because the generated files are what Akhilesh builds against and he
 * will never read our TypeScript.
 */

const OUT = join(import.meta.dirname, "..", "..", "..", "..", "docs", "ue5-contract");

describe("the generated contract is current", () => {
  const artefacts = generatedArtefacts();

  it("produces an OpenAPI document and a schema for every component", () => {
    expect(artefacts.has("openapi.json")).toBe(true);
    const schemas = [...artefacts.keys()].filter((name) => name.startsWith("schemas/"));
    expect(schemas.length).toBeGreaterThan(8);
  });

  it("matches every committed file, byte for byte", () => {
    for (const [relative, expected] of artefacts) {
      const committed = readFileSync(join(OUT, relative), "utf8");
      expect(committed, `${relative} is stale — run \`pnpm contracts:ue5\``).toBe(expected);
    }
  });

  it("leaves nothing behind that the generator no longer produces", () => {
    const onDisk = new Set<string>();
    for (const entry of readdirSync(OUT, { withFileTypes: true, recursive: true })) {
      if (entry.isFile()) {
        const parent = entry.parentPath.slice(OUT.length + 1).replace(/\\/g, "/");
        const relative = parent === "" ? entry.name : `${parent}/${entry.name}`;
        /*
         * `fixtures/` is a second generator's output (`pnpm contracts:fixtures`)
         * and has its own drift test in `fixtures.test.ts`. Counting it here
         * would make this file fail for a pack it does not produce.
         */
        if (relative.startsWith(`${UE5_FIXTURE_DIRECTORY}/`)) continue;
        onDisk.add(relative);
      }
    }
    expect([...onDisk].sort()).toEqual([...artefacts.keys()].sort());
  });
});

describe("the OpenAPI document says the things it must", () => {
  const document: Record<string, unknown> = buildOpenApiDocument();
  const at = <T>(key: string): T => document[key] as T;

  it("is OpenAPI 3.1, so the schemas go in as JSON Schema 2020-12", () => {
    expect(document["openapi"]).toBe("3.1.0");
  });

  it("describes the three proposed endpoints and nothing more", () => {
    expect(Object.keys(at<object>("paths")).sort()).toEqual([
      "/observer-activate",
      "/observer-heartbeat",
      "/observer-ingest",
    ]);
  });

  it("leaves activation unauthenticated and secures the other two", () => {
    const paths = at<Record<string, Record<string, Record<string, unknown>>>>("paths");
    expect(paths["/observer-activate"]?.["post"]?.["security"]).toBeUndefined();
    expect(paths["/observer-ingest"]?.["post"]?.["security"]).toEqual([{ sourceToken: [] }]);
    expect(paths["/observer-heartbeat"]?.["post"]?.["security"]).toEqual([{ sourceToken: [] }]);
  });

  it("says plainly that it is a proposal", () => {
    const contract = at<Record<string, string>>("x-observer-contract");
    expect(contract["status"]).toBe("PROPOSED");
    expect(contract["version"]).toContain("candidate");
  });

  it("carries the whole error model, so a client needs no other file", () => {
    const contract = at<Record<string, unknown[]>>("x-observer-contract");
    expect((contract["requestFailures"] ?? []).length).toBeGreaterThan(4);
    expect((contract["eventRejections"] ?? []).length).toBeGreaterThan(6);
  });

  it("gives the activation response no tenant or project identifier", () => {
    const schemas = at<{ schemas: Record<string, { properties: Record<string, unknown> }> }>(
      "components",
    );
    const success = schemas.schemas["ActivationSuccess"];
    expect(Object.keys(success?.properties ?? {})).not.toContain("tenant_id");
    expect(Object.keys(success?.properties ?? {})).not.toContain("project_id");
    expect(Object.keys(success?.properties ?? {})).toContain("source_id");
  });

  it("closes every envelope a client sends", () => {
    const schemas = at<{ schemas: Record<string, { additionalProperties?: unknown }> }>(
      "components",
    );
    for (const name of [
      "ActivationRequest",
      "BatchEnvelope",
      "EventEnvelope",
      "HeartbeatRequest",
    ]) {
      expect(schemas.schemas[name]?.additionalProperties, name).toBe(false);
    }
  });
});
