-- Observer — who wrote the answer, and did every admitted request leave a trace?
--
-- Two defects, found by verifying the deployment rather than the code.
--
-- **The audit could not say who wrote the prose.** `outcome` was `answered`
-- whenever an answer existed, and `model` held the *configured* model name
-- whether or not that model had written a word. A deterministic fallback —
-- which the screen labels honestly as "written by the tools" — was recorded as
-- `answered · gpt-5.6-sol`. The one question worth asking of an AI feature's
-- audit is which answers the AI actually wrote, and this table answered it
-- wrongly.
--
-- **The audit lost requests.** 153 admitted against 133 rows. The write was
-- fire-and-forget from a serverless route, which can freeze after the response
-- and drop an unawaited promise — but that was a hypothesis, and a hypothesis
-- is not a fix. The invariant is now structural instead: the row is inserted in
-- the *same transaction* that consumes the quota, so a request cannot be
-- admitted without leaving a trace. An interruption after that leaves the row
-- in `started`, which is a fact about the request rather than a silence.
--
-- What is still never stored: the question, the answer, any prompt, any tool
-- argument, any provider error body, any key, any person. The columns below are
-- codes, counts and timings.

/* --- the columns ---------------------------------------------------------- */

-- `model` recorded the model that was *attempted*, whatever happened next. That
-- is a useful fact under an accurate name, so it keeps its data and loses its
-- misleading one. Guarded so re-running this migration is harmless.
do $$
begin
  if exists (
    select 1 from information_schema.columns
     where table_schema = 'observer' and table_name = 'ai_requests' and column_name = 'model'
  ) and not exists (
    select 1 from information_schema.columns
     where table_schema = 'observer' and table_name = 'ai_requests' and column_name = 'attempted_model'
  ) then
    alter table observer.ai_requests rename column model to attempted_model;
  end if;
end $$;

alter table observer.ai_requests
  -- Stable across retries, generated by the route, unique. The join between
  -- "the quota admitted this" and "this is what happened to it".
  add column if not exists request_id uuid,
  -- `started` until the route reports a terminal result. A row that stays
  -- `started` is an interrupted request, which is exactly what the old design
  -- could not distinguish from a request that never existed.
  add column if not exists state text not null default 'started',
  -- model | deterministic_composer | refusal | failure
  add column if not exists response_source text,
  add column if not exists attempted_provider text,
  add column if not exists attempted_model text,
  add column if not exists model_attempted boolean not null default false,
  -- Must equal the `live` flag the answer sheet renders. Same fact, two places,
  -- and a test asserts they cannot drift.
  add column if not exists model_authored boolean not null default false,
  -- Null unless the model wrote the final prose. Never the configured name.
  add column if not exists author_model text,
  -- A code, never a provider message: an upstream error body can quote the
  -- request back, and the request carries project evidence.
  add column if not exists fallback_reason text,
  add column if not exists completed_at timestamptz;

comment on column observer.ai_requests.attempted_model is
  'The model this request tried to use. Says nothing about who wrote the prose.';
comment on column observer.ai_requests.author_model is
  'The model that wrote the final prose, or null. Null is the honest answer for every fallback.';
comment on column observer.ai_requests.fallback_reason is
  'Why the deterministic composer answered instead. A fixed code, never a provider message.';

-- `occurred_at` now marks admission rather than completion, because that is
-- when the row is written. `completed_at` marks the terminal result.
comment on column observer.ai_requests.occurred_at is
  'When the request was admitted by the quota gate.';

-- A terminal outcome is not known at admission.
alter table observer.ai_requests alter column outcome drop not null;
alter table observer.ai_requests alter column question_chars drop not null;

-- One admitted request, one row. Also what makes the insert idempotent under a
-- retry: Postgres allows many nulls here, so historical rows are untouched.
create unique index if not exists ai_requests_request_id_key
  on observer.ai_requests (request_id);

create index if not exists ai_requests_state_idx
  on observer.ai_requests (state) where state <> 'complete';

/* --- admission: the ceiling and the trace, in one transaction -------------- */

-- The ceiling logic is not repeated here. `observer.consume_ai_quota` remains
-- the single implementation and this wraps it, so there is one place where a
-- limit is decided and one place to change it.
--
-- The insert runs only when the quota allowed the request, and shares its
-- transaction — which is what makes "admitted" and "audited" the same event
-- rather than two events that usually coincide.
create or replace function observer.admit_ai_request(
  p_request_id      uuid,
  p_session         text,
  p_client_hash     text,
  p_project         text,
  p_per_minute      integer,
  p_per_hour        integer,
  p_client_per_hour integer,
  p_project_per_day integer,
  p_tenant_slug     text,
  p_project_slug    text,
  p_viewer_role     text,
  p_question_chars  integer
)
returns table (allowed boolean, reason text, retry_after_seconds integer)
language plpgsql
security definer
set search_path = observer, pg_catalog
as $$
declare
  v_allowed boolean;
  v_reason  text;
  v_retry   integer;
begin
  select q.allowed, q.reason, q.retry_after_seconds
    into v_allowed, v_reason, v_retry
    from observer.consume_ai_quota(
      p_session, p_client_hash, p_project,
      p_per_minute, p_per_hour, p_client_per_hour, p_project_per_day
    ) q;

  if v_allowed then
    insert into observer.ai_requests (
      request_id, subject, client_hash, tenant_slug, project_slug, viewer_role,
      state, question_chars
    ) values (
      p_request_id, p_session, p_client_hash, p_tenant_slug, p_project_slug, p_viewer_role,
      'started', p_question_chars
    )
    -- A retried admission must not produce a second row.
    on conflict (request_id) do nothing;
  end if;

  return query select v_allowed, v_reason, v_retry;
end;
$$;

/* --- completion: the terminal result -------------------------------------- */

-- Idempotent by construction: it updates one row by its id, so calling it twice
-- with the same result changes nothing the second time. Returns whether a row
-- matched, so the route can log a miss instead of assuming success.
create or replace function observer.complete_ai_request(
  p_request_id        uuid,
  p_outcome           text,
  p_response_source   text,
  p_attempted_provider text,
  p_attempted_model   text,
  p_model_attempted   boolean,
  p_model_authored    boolean,
  p_author_model      text,
  p_fallback_reason   text,
  p_tools             text[],
  p_tool_calls        integer,
  p_input_tokens      integer,
  p_output_tokens     integer,
  p_latency_ms        integer
)
returns boolean
language plpgsql
security definer
set search_path = observer, pg_catalog
as $$
declare
  v_matched integer;
begin
  update observer.ai_requests
     set state             = 'complete',
         completed_at      = now(),
         outcome           = p_outcome,
         response_source   = p_response_source,
         attempted_provider = p_attempted_provider,
         attempted_model   = p_attempted_model,
         model_attempted   = coalesce(p_model_attempted, false),
         model_authored    = coalesce(p_model_authored, false),
         author_model      = p_author_model,
         fallback_reason   = p_fallback_reason,
         tools             = coalesce(p_tools, '{}'),
         tool_calls        = coalesce(p_tool_calls, 0),
         input_tokens      = p_input_tokens,
         output_tokens     = p_output_tokens,
         latency_ms        = p_latency_ms
   where request_id = p_request_id;

  get diagnostics v_matched = row_count;
  return v_matched > 0;
end;
$$;

-- Postgres grants EXECUTE on a new function to PUBLIC by default. Nothing can
-- reach these two anyway — the `observer` schema has no USAGE for a browser
-- role and PostgREST does not expose it — but the posture in this schema is an
-- explicit revoke on every object, and defence that relies on one layer holding
-- is not defence.
revoke all on function observer.admit_ai_request(uuid, text, text, text, integer, integer, integer, integer, text, text, text, integer)
  from anon, authenticated, public;
revoke all on function observer.complete_ai_request(uuid, text, text, text, text, boolean, boolean, text, text, text[], integer, integer, integer, integer)
  from anon, authenticated, public;

/* --- the reachable surface ------------------------------------------------- */

create or replace function public.admit_ai_request(
  p_request_id      uuid,
  p_session         text,
  p_client_hash     text,
  p_project         text,
  p_per_minute      integer,
  p_per_hour        integer,
  p_client_per_hour integer,
  p_project_per_day integer,
  p_tenant_slug     text,
  p_project_slug    text,
  p_viewer_role     text,
  p_question_chars  integer
)
returns table (allowed boolean, reason text, retry_after_seconds integer)
language sql
security definer
set search_path = public, pg_catalog
as $$
  select * from observer.admit_ai_request(
    p_request_id, p_session, p_client_hash, p_project,
    p_per_minute, p_per_hour, p_client_per_hour, p_project_per_day,
    p_tenant_slug, p_project_slug, p_viewer_role, p_question_chars
  );
$$;

comment on function public.admit_ai_request(uuid, text, text, text, integer, integer, integer, integer, text, text, text, integer) is
  'The only door to the shared Ask Observer ceiling. Consuming it and recording the request are one transaction.';

create or replace function public.complete_ai_request(
  p_request_id        uuid,
  p_outcome           text,
  p_response_source   text,
  p_attempted_provider text,
  p_attempted_model   text,
  p_model_attempted   boolean,
  p_model_authored    boolean,
  p_author_model      text,
  p_fallback_reason   text,
  p_tools             text[],
  p_tool_calls        integer,
  p_input_tokens      integer,
  p_output_tokens     integer,
  p_latency_ms        integer
)
returns boolean
language sql
security definer
set search_path = public, pg_catalog
as $$
  select observer.complete_ai_request(
    p_request_id, p_outcome, p_response_source, p_attempted_provider, p_attempted_model,
    p_model_attempted, p_model_authored, p_author_model, p_fallback_reason,
    p_tools, p_tool_calls, p_input_tokens, p_output_tokens, p_latency_ms
  );
$$;

comment on function public.complete_ai_request(uuid, text, text, text, text, boolean, boolean, text, text, text[], integer, integer, integer, integer) is
  'Records the terminal result of an already-admitted request. Idempotent; returns whether a row matched.';

revoke all on function public.admit_ai_request(uuid, text, text, text, integer, integer, integer, integer, text, text, text, integer)
  from anon, authenticated, public;
revoke all on function public.complete_ai_request(uuid, text, text, text, text, boolean, boolean, text, text, text[], integer, integer, integer, integer)
  from anon, authenticated, public;

grant execute on function public.admit_ai_request(uuid, text, text, text, integer, integer, integer, integer, text, text, text, integer)
  to service_role;
grant execute on function public.complete_ai_request(uuid, text, text, text, text, boolean, boolean, text, text, text[], integer, integer, integer, integer)
  to service_role;

/* --- what this supersedes -------------------------------------------------- */

-- Two doors to the same counters is the drift this codebase avoids. The
-- implementation inside `observer` stays — `admit_ai_request` calls it — and
-- only the reachable façades go.
--
-- Sequencing matters and is stated rather than assumed: apply this migration
-- *before* deploying the code that calls the new names. Between the two, the
-- running build calls functions that no longer exist, the ceiling fails closed,
-- and Ask Observer refuses for as long as the deploy takes. Every measured
-- figure on every screen is unaffected, which is what makes that window
-- affordable.
drop function if exists public.consume_ai_quota(text, text, text, integer, integer, integer, integer);
drop function if exists public.record_ai_request(text, text, text, text, text, text, text, text[], integer, integer, integer, integer, integer);

/* --- the diagnostic leaves the browser ------------------------------------- */

-- `observer_whoami` earned its place: it proved the deployment was talking to a
-- different Supabase project by answering 200 to one caller and 404 to another.
-- That question is settled, and a release candidate should not ship a function
-- any holder of the browser key can call, however harmless its answer.
--
-- Revoked rather than dropped. It runs as the caller by design, which is the
-- whole point of it, and an operator holding the server key may still need to
-- ask which role they are. It is simply no longer reachable from a browser.
revoke execute on function public.observer_whoami() from anon, authenticated, public;
